#
## DEFINITION OF THE ARENA
#

use_utm_origin: true
utm_origin_x: 465710.758973
utm_origin_y: 5249465.43086

use_local_origin: false
local_origin_x: 0.0
local_origin_y: 0.0

safety_area:

  use_safety_area: true

  # convex polygon CCW
  safety_area: [30.9, 26.4,
  -45.0, 7.27,
  -31.5, -38.0,
  44.5, -23.5]

  max_height: 10.0
  min_height: 0.5
